apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-java-deployment
  labels:
    app: microservice-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-java
  template:
    metadata:
      labels:
        app: microservice-java
    spec:
      containers:
      - name: microservice-java
        image: vpmlagos/microservice-java:latest #parametrizar latest 
        ports:
        - containerPort: 8080