name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

  
      - name: Análisis SonarCloud
        run: |
          chmod +x ./gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      
      - name: Sonar Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master 
        env: 
          SONAR_TOKEN = ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL = ${{ secrets.SONAR_HOST_URL }}
        with:
          scanMetadataReportFile: build/sonar/report-task.txt

      