name: CI
on:
  push:
    branches: [ "feature-ms-valentinaMoreno-mensaje" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

  code_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Análisis SonarCloud
        run: |
          chmod +x ./gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Realizar tests
        run: |
          chmod +x ./gradlew
          ./gradlew test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker access
      - uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
      - uses: actions/checkout@v3
      - name: Despliegue
      run: |
        docker build --tag vpmlagos/microservicio-java:latest .
        
      
      - name: Docker push
      run: |
        docker push vpmlagos/microservicio-java:latest
        
