name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

  
      - name: Análisis SonarCloud
        run: |
          chmod +x ./gradlew
          ./gradlew jacocoTestReport sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }} --info --stacktrace
      
      - name: Sonar Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          scanMetadataReportFile: build/sonar/report-task.txt


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login docker
      - uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build
      run: |
        docker build --tag vpmlagos/microservicio-java:latest
        

    #runs-on: ubuntu-latest
    #needs: build
    #steps:
    #  - uses: actions/checkout@v3
    #  - name: Deploy
    #    run: |
    #      kubectl apply -f deployment.yml